services:
  api: 
    # 主API服务器
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    container_name: backend-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  celery: 
    # 负责消费MQ中的任务，更新用户的基本信息
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: backend-celery
    command: celery --app tasks.main:celery_app worker -Q refresh_queue --loglevel=info --concurrency=4
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  beat: 
    # 定时任务，负责：
    # 1.定期更新服务器数据
    # 2.定时刷新用户授权数据
    # 3.检测并更新更新用户token
    build: .
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    container_name: backend-beat
    command: python scripts/beat/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  maintenance: 
    # 维护进程，负责
    # 1.更新在线用户
    # 2.更新游戏版本
    # 3.维护用户活跃信息
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: backend-maintenance
    command: python scripts/maintenance/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  cache: 
    # 更新用户的船只缓存数据，主要负责排行榜数据
    build: .
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    container_name: scheduler-cache
    command: python scripts/scheduler/cache/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  users: # 更新工会的成员数据
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: scheduler-users
    command: python scripts/scheduler/users/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  clan: # 更新工会的数据
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: scheduler-clan
    command: python scripts/scheduler/clan/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  recent: # Recent功能
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    container_name: backend-recent
    command: python scripts/recent/main.py
    env_file:
      - .env.dev
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
