services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - env.prod
    command: >
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis7
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - env.prod
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data # 数据持久化
      - ./redis.conf:/usr/local/etc/redis/redis.conf # 配置文件挂载

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq4
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - env.prod
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    image: myapp:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    container_name: backend-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --log-level info
    env_file:
      - env.prod
    ports:
      - "0.0.0.0:80:80"
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  celery:
    image: myapp:latest
    volumes:
      - ./logs:/app/logs
    container_name: backend-celery
    command: celery --app tasks.main:celery_app worker -Q refresh_queue --loglevel=info --concurrency=2
    env_file:
      - env.prod
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  maintenance:
    image: myapp:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    container_name: backend-maintenance
    command: python scripts/maintenance/main.py
    env_file:
      - env.prod
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  cache:
    image: myapp:latest
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    container_name: backend-cache
    command: python scripts/cache/main.py
    env_file:
      - env.prod
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  season:
    image: myapp:latest
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    container_name: backend-season
    command: python scripts/season/main.py
    env_file:
      - env.prod
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  stats:
    image: myapp:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    container_name: backend-stats
    command: python scripts/stats/main.py
    env_file:
      - env.prod
    restart: on-failure:1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # recent:
  #   image: myapp:latest
  #   volumes:
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #   container_name: backend-recent
  #   command: python scripts/recent/main.py
  #   env_file:
  #     - .env.prod
  #   restart: on-failure:1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"

# 命名卷
volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
